name: 🐞 Bug report
description: Something isn't working as it should
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to …
        2. Click …
        3. See …
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 0.1.0
  - type: dropdown
    id: server
    attributes:
      label: Media server
      options: ["N/A", "Plex", "Jellyfin", "Emby"]
